# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dx < Formula
  desc "CLI for Deductive AI — ask questions about your infrastructure"
  homepage "https://deductive.ai"
  version "0.5.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deductive-ai/dx/releases/download/v0.5.1/dx_0.5.1_darwin_amd64.tar.gz"
      sha256 "15afcf2c162eb6a802656ff190a5723d3732ba3a8897fa790c0cc6e5765164c3"

      define_method(:install) do
        bin.install "dx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deductive-ai/dx/releases/download/v0.5.1/dx_0.5.1_darwin_arm64.tar.gz"
      sha256 "b5c566425e8fecd63e3a1dad480d4e608f7f3554f8a4dd416f2f6e0dfb792886"

      define_method(:install) do
        bin.install "dx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/deductive-ai/dx/releases/download/v0.5.1/dx_0.5.1_linux_amd64.tar.gz"
      sha256 "6442a5e856c1f40f14ea4f98bc2658fe6963e40869eeae19c269abf650fe48f7"
      define_method(:install) do
        bin.install "dx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deductive-ai/dx/releases/download/v0.5.1/dx_0.5.1_linux_arm64.tar.gz"
      sha256 "0b584a26e4492d6a13e739c169ab30009bb9fd71895dbae55f9d12a0cfcafd24"
      define_method(:install) do
        bin.install "dx"
      end
    end
  end

  test do
    system "#{bin}/dx", "version"
  end
end
